# Generated by Django 3.2.1 on 2021-07-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFeed', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
